CREATE TABLE IF NOT EXISTS  validation_codes (
  id  SERIAL  PRIMARY KEY,
  code VARCHAR(20) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  used_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

