basePath: /api/v1
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:3000
info:
  contact:
    email: vino0908@outlook.com
    name: vino
    url: https://baidu.com
  title: Naruto Go API
  version: "1.0"
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: Ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Ping
      tags:
      - Ping
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
